import {
	Address,
	BookingDetails,
	SponsoredProduct,
	Transaction,
	WhishlistProduct,
} from '@/interfaces/interface';

export const bookingData: BookingDetails[] = [
	{
		id: 1,
		bookingId: 'BK000001',
		serviceName: 'Lawn Mowing Service',
		startTime: '2025-06-06T10:00:00.000Z',
		address: '123 Powerline Ave, Spark City',
		duration: 1.5,
		status: 'upcoming',
		serviceImage:
			'https://images.unsplash.com/photo-1683316924890-6a8c5ab10d29?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		serviceProvider: {
			id: 101,
			name: 'GreenCare Experts',
			rating: 4.8,
			ratePerHour: 700,
			totalReviews: 152,
			profileImage: 'https://example.com/provider1.jpg',
			phone: '+1234567890',
			email: 'contact@greencare.com',
		},
		paymentMethod: {
			id: 'pm_1',
			type: 'card',
			displayName: 'Visa •••• 4242',
			last4: '4242',
			cardBrand: 'visa',
			icon: 'https://example.com/icons/visa.png',
		},
		serviceDetails: {
			description: 'Professional lawn mowing with edge trimming.',
			equipment: ['Mower', 'Trimmer'],
			instructions: 'Ensure pets are indoors during service.',
			estimatedCost: 1050,
			paymentStatus: 'pending',
		},
	},
	{
		id: 2,
		bookingId: 'BK000002',
		serviceName: 'Garden Landscaping',
		startTime: '2025-06-08T09:00:00.000Z',
		address: '456 Garden St, Green Valley',
		duration: 3,
		status: 'upcoming',
		serviceImage:
			'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg',
		remindMe: false,
		serviceProvider: {
			id: 102,
			name: 'Nature Builders',
			rating: 4.6,
			ratePerHour: 1200,
			totalReviews: 200,
			profileImage: 'https://example.com/provider2.jpg',
			phone: '+1987654321',
			email: 'info@naturebuilders.com',
		},
		paymentMethod: {
			id: 'pm_2',
			type: 'paypal',
			displayName: 'PayPal',
			icon: 'https://example.com/icons/paypal.png',
		},
		serviceDetails: {
			description: 'Full landscaping including new plant installation.',
			equipment: ['Shovel', 'Wheelbarrow', 'Plants'],
			instructions: 'Mark preferred planting areas beforehand.',
			estimatedCost: 3600,
			paymentStatus: 'pending',
		},
	},
	{
		id: 3,
		bookingId: 'BK000003',
		serviceName: 'Tree Pruning Service',
		startTime: '2025-05-25T11:00:00.000Z',
		address: '789 Oak Avenue, Leaf Town',
		serviceImage:
			'https://images.pexels.com/photos/4986333/pexels-photo-4986333.jpeg',
		duration: 2,
		status: 'completed',
		serviceProvider: {
			id: 103,
			name: 'TreeMasters',
			rating: 4.9,
			ratePerHour: 1000,
			totalReviews: 95,
			profileImage: 'https://example.com/provider3.jpg',
			phone: '+1122334455',
			email: 'support@treemasters.com',
		},
		paymentMethod: {
			id: 'pm_3',
			type: 'apple_pay',
			displayName: 'Apple Pay',
			icon: 'https://example.com/icons/applepay.png',
		},
		serviceDetails: {
			description: 'Expert tree pruning for health and shape.',
			equipment: ['Pruner', 'Ladder'],
			instructions: 'Provide safe ladder access.',
			estimatedCost: 2000,
			paymentStatus: 'paid',
		},
	},
	{
		id: 4,
		bookingId: 'BK000004',
		serviceName: 'Garden Cleanup',
		startTime: '2025-09-15T09:30:00.000Z',
		serviceImage:
			'https://images.pexels.com/photos/26827231/pexels-photo-26827231.jpeg',
		address: '45 Greenway Blvd, Springfield, IL 62701',
		duration: 2,
		status: 'upcoming',
		remindMe: true,
		notes: 'Please remove fallen branches and trim the hedges near the fence.',
		serviceProvider: {
			id: 4,
			name: 'Alice Johnson',
			rating: 4.9,
			totalReviews: 212,
			ratePerHour: 70,
			profileImage: '',
			phone: '+1 (555) 654-7890',
			email: 'alice.johnson@gardenpros.com',
		},
		serviceDetails: {
			description:
				'Comprehensive garden cleanup including hedge trimming, branch removal, and lawn edging.',
			equipment: ['Hedge trimmer', 'Rake', 'Leaf bags', 'Wheelbarrow'],
			instructions:
				'Focus on the back garden and dispose of waste in compost bins.',
			estimatedCost: 140,
			paymentStatus: 'pending',
		},
		paymentMethod: {
			id: 'card_234',
			type: 'card',
			displayName: 'Visa **** 9876',
			icon: 'card-outline',
		},
	},
	{
		id: 5,
		bookingId: 'BK000005',
		serviceName: 'Tree Pruning',
		startTime: '2025-08-28T14:00:00.000Z',
		address: '99 Oak Street, Denver, CO 80205',
		serviceImage:
			'https://images.pexels.com/photos/4986333/pexels-photo-4986333.jpeg',
		duration: 3,
		status: 'completed',
		remindMe: false,
		notes: 'Trim the oak tree branches hanging over the driveway.',
		serviceProvider: {
			id: 5,
			name: 'Michael Brown',
			rating: 4.7,
			totalReviews: 95,
			ratePerHour: 85,
			profileImage: '',
			phone: '+1 (555) 777-4567',
			email: 'michael.brown@treeservices.com',
		},
		serviceDetails: {
			description:
				'Professional pruning and trimming for large and medium-sized trees.',
			equipment: ['Chainsaw', 'Ladders', 'Safety gear'],
			instructions: 'Dispose cut branches in the yard waste bin.',
			estimatedCost: 255,
			paymentStatus: 'paid',
		},
		paymentMethod: {
			id: 'paypal_789',
			type: 'paypal',
			displayName: 'PayPal',
			icon: 'logo-paypal',
		},
	},
	{
		id: 6,
		bookingId: 'BK000006',
		serviceName: 'Flower Bed Planting',
		startTime: '2025-10-03T11:00:00.000Z',
		address: '12 Rosewood Lane, Austin, TX 73301',
		duration: 1.5,
		serviceImage:
			'https://images.unsplash.com/photo-1630257334364-d1dfe34cc166?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
		status: 'cancelled',
		remindMe: false,
		notes: 'Plant seasonal flowers and add fresh mulch.',
		serviceProvider: {
			id: 6,
			name: 'Sophie Lee',
			rating: 4.6,
			totalReviews: 180,
			ratePerHour: 60,
			profileImage: '',
			phone: '+1 (555) 888-9999',
			email: 'sophie.lee@flowerdesigns.com',
		},
		serviceDetails: {
			description:
				'Planting and arranging seasonal flowers with soil preparation and mulching.',
			equipment: ['Shovel', 'Mulch bags', 'Gloves'],
			instructions: 'Focus on front yard beds, arrange colors symmetrically.',
			estimatedCost: 90,
			paymentStatus: 'refunded',
		},
		paymentMethod: {
			id: 'apple_123',
			type: 'google_pay',
			displayName: 'Google Pay',
			icon: 'logo-apple',
		},
	},
];

export const DUMMY_WISHLIST_ITEMS: WhishlistProduct[] = [
	{
		id: '1',
		name: 'Monstera Deliciosa Outdoor Plant',
		price: 45.0,
		image: 'https://placehold.co/100',
		category: 'Plants',
		inStock: true,
	},
	{
		id: '2',
		name: 'Ceramic Plant Pot',
		price: 29.0,
		image: 'https://placehold.co/100',
		category: 'Accessories',
		inStock: true,
	},
	{
		id: '3',
		name: 'Snake Plant',
		price: 35.0,
		image: 'https://placehold.co/100',
		category: 'Plants',
		inStock: true,
	},
	{
		id: '4',
		name: 'Plant Care Kit',
		price: 65.0,
		image: 'https://placehold.co/100',
		category: 'Accessories',
		inStock: false,
	},
	{
		id: '5',
		name: 'Fiddle Leaf Fig',
		price: 89.0,
		image: 'https://placehold.co/100',
		category: 'Plants',
		inStock: true,
	},
	{
		id: '6',
		name: 'Watering Can',
		price: 25.0,
		image: 'https://placehold.co/100',
		category: 'Accessories',
		inStock: true,
	},
	{
		id: '7',
		name: 'Peace Lily',
		price: 32.0,
		image: 'https://placehold.co/100',
		category: 'Plants',
		inStock: true,
	},
	{
		id: '8',
		name: 'Plant Fertilizer',
		price: 18.0,
		image: 'https://placehold.co/100',
		category: 'Accessories',
		inStock: true,
	},
	{
		id: '9',
		name: 'Rubber Plant',
		price: 42.0,
		image: 'https://placehold.co/100',
		category: 'Plants',
		inStock: true,
	},
	{
		id: '10',
		name: 'Plant Stand',
		price: 75.0,
		image: 'https://placehold.co/100',
		category: 'Accessories',
		inStock: true,
	},
];

export const dummyTransactions: Transaction[] = [
	{
		id: '1',
		title: 'Plant Purchase',
		amount: 1500,
		date: '2025-09-12',
		type: 'debit',
	},
	{ id: '2', title: 'Refund', amount: 500, date: '2025-09-11', type: 'credit' },
	{
		id: '3',
		title: 'Pot Purchase',
		amount: 800,
		date: '2025-09-10',
		type: 'debit',
	},
	{
		id: '4',
		title: 'Soil Bag',
		amount: 300,
		date: '2025-09-09',
		type: 'debit',
	},
	{
		id: '5',
		title: 'Garden Tools',
		amount: 1200,
		date: '2025-09-08',
		type: 'debit',
	},
	{
		id: '6',
		title: 'Cashback Bonus',
		amount: 200,
		date: '2025-09-07',
		type: 'credit',
	},

	// 👇 new ones starting from id 7
	{
		id: '7',
		title: 'Fertilizer Purchase',
		amount: 650,
		date: '2025-09-06',
		type: 'debit',
	},
	{
		id: '8',
		title: 'Planter Refund',
		amount: 400,
		date: '2025-09-05',
		type: 'credit',
	},
	{
		id: '9',
		title: 'Flower Seeds',
		amount: 150,
		date: '2025-09-04',
		type: 'debit',
	},
	{
		id: '10',
		title: 'Tree Sapling',
		amount: 2200,
		date: '2025-09-03',
		type: 'debit',
	},
	{
		id: '11',
		title: 'Promo Reward',
		amount: 100,
		date: '2025-09-02',
		type: 'credit',
	},
	{
		id: '12',
		title: 'Gardening Gloves',
		amount: 350,
		date: '2025-09-01',
		type: 'debit',
	},
	{
		id: '13',
		title: 'Soil Delivery Fee Refund',
		amount: 150,
		date: '2025-08-31',
		type: 'credit',
	},
	{
		id: '14',
		title: 'Decorative Stones',
		amount: 900,
		date: '2025-08-30',
		type: 'debit',
	},
	{
		id: '15',
		title: 'Herb Seeds',
		amount: 250,
		date: '2025-08-29',
		type: 'debit',
	},
	{
		id: '16',
		title: 'Referral Bonus',
		amount: 500,
		date: '2025-08-28',
		type: 'credit',
	},
];

export const mockAddresses: Address[] = [
	{
		_id: '1',
		name: 'Ali Usman',
		email: 'aliusman429040@gmail.com',
		fullAddress: '3311 Crescent Day, La Port, California, United States 77571',
		phone: '(+92) 316 6103232',
		isDefault: false,
		label: 'Home',
		city: 'Pattoki',
		province: 'Punjab',
		country: 'Pakistan',
	},
	{
		_id: '2',
		name: 'Ali Usman',
		email: 'mrau429040@gmail.com',
		fullAddress: '3311 Crescent Day, La Port, California, United States 77571',
		phone: '0316 6183522',
		isDefault: true,
		label: 'Office',
		city: 'Pattoki',
		province: 'Punjab',
		country: 'Pakistan',
	},
	// {
	// 	id: '3',
	// 	name: 'Ali Usman',
	// 	fullAddress: '3311 Crescent Day, La Port, California, United States 77571',
	// 	phone: '+92 316 6103232',
	// 	isDefault: true,
	// 	type: 'school',
	// },
	// {
	// 	id: '4',
	// 	name: 'Ali Usman',
	// 	fullAddress: '3311 Crescent Day, La Port, California, United States 77571',
	// 	phone: '+92 316 6103232',
	// 	isDefault: false,
	// 	type: 'school',
	// },
	// {
	// 	id: '5',
	// 	name: 'Ali Usman',
	// 	fullAddress: '3311 Crescent Day, La Port, California, United States 77571',
	// 	phone: '+92 316 6103232',
	// 	isDefault: false,
	// 	type: 'school',
	// },
];

export const mockSponsoredProducts: SponsoredProduct[] = [
	{
		id: 'sp1',
		productId: 'p1',
		vendorId: 'v1',
		startDate: '2025-09-01T00:00:00.000Z',
		endDate: '2025-09-30T23:59:59.000Z',
		position: 'homepage',
		bidAmount: 10,
		priority: 1,
		impressions: 1200,
		clicks: 80,
		isActive: true,
		punchLine: 'Upto 40% off',
		title: 'Best plant awaits',
		product: {
			id: 'p1',
			name: 'Rose Plant',
			price: 250,
			image: '/images/rose.jpg',
			rating: 4.5,
			reviewCount: 120,
			badge: ['Hot'],
		},
	},
	{
		id: 'sp2',
		productId: 'p2',
		vendorId: 'v2',
		startDate: '2025-09-05T00:00:00.000Z',
		endDate: '2025-10-05T23:59:59.000Z',
		position: 'homepage',
		bidAmount: 8,
		priority: 2,
		impressions: 900,
		clicks: 65,
		punchLine: 'PKR 799 P̶K̶R̶ ̶9̶0̶0̶',
		title: 'Sale is live!',
		isActive: true,
		product: {
			id: 'p2',
			name: 'Snake Plant',
			price: 400,
			image: '/images/snakeplant.jpg',
			rating: 4.7,
			reviewCount: 85,
			badge: ['New'],
		},
	},
	{
		id: 'sp3',
		productId: 'p3',
		vendorId: 'v1',
		startDate: '2025-09-10T00:00:00.000Z',
		endDate: '2025-10-15T23:59:59.000Z',
		position: 'category',
		bidAmount: 6,
		priority: 3,
		impressions: 500,
		clicks: 40,
		punchLine: 'Shop Now',
		title: 'Cheapest Plants',
		isActive: true,
		product: {
			id: 'p3',
			name: 'Aloe Vera',
			price: 180,
			image: '/images/aloevera.jpg',
			rating: 4.3,
			reviewCount: 60,
		},
	},
	{
		id: 'sp4',
		productId: 'p4',
		vendorId: 'v3',
		startDate: '2025-08-20T00:00:00.000Z',
		endDate: '2025-09-25T23:59:59.000Z',
		position: 'search',
		bidAmount: 12,
		priority: 1,
		punchLine: 'Just PKR 199',
		title: 'Outdoor Plants',
		impressions: 1500,
		clicks: 110,
		isActive: true,
		product: {
			id: 'p4',
			name: 'Fiddle Leaf Fig',
			price: 1200,
			image: '/images/fiddle.jpg',
			rating: 4.6,
			reviewCount: 200,
		},
	},
	{
		id: 'sp5',
		productId: 'p5',
		vendorId: 'v4',
		startDate: '2025-09-15T00:00:00.000Z',
		endDate: '2025-10-15T23:59:59.000Z',
		position: 'homepage',
		bidAmount: 7,
		priority: 4,
		impressions: 600,
		punchLine: 'Cheapest Accessories',
		title: 'Beautify your Lawn!',
		clicks: 30,
		isActive: true,
		product: {
			id: 'p5',
			name: 'Bonsai Tree',
			price: 2200,
			image: '/images/bonsai.jpg',
			rating: 4.9,
			reviewCount: 340,
		},
	},
	{
		id: 'sp6',
		productId: 'p6',
		vendorId: 'v5',
		startDate: '2025-09-12T00:00:00.000Z',
		endDate: '2025-10-12T23:59:59.000Z',
		position: 'category',
		punchLine: 'Upto 50% off',
		title: 'Pots & Other',
		bidAmount: 5,
		priority: 5,
		impressions: 300,
		clicks: 15,
		isActive: true,
		product: {
			id: 'p6',
			name: 'Money Plant',
			price: 320,
			image: '/images/moneyplant.jpg',
			rating: 4.4,
			reviewCount: 75,
		},
	},
];
